# Generated by Django 4.2.7 on 2025-11-05 18:32

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='codigo_barra',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='unidadmedida',
            name='abreviatura',
        ),
        migrations.RemoveField(
            model_name='unidadmedida',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='unidadmedida',
            name='fecha_modificacion',
        ),
        migrations.AddField(
            model_name='categoria',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoria',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='alerta_por_vencer',
            field=models.BooleanField(default=False, help_text='Indica si hay productos próximos a vencer', verbose_name='Alerta Por Vencer'),
        ),
        migrations.AddField(
            model_name='producto',
            name='costo_estandar',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo promedio estándar del producto', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Costo Estándar'),
        ),
        migrations.AddField(
            model_name='producto',
            name='costo_promedio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculado automáticamente con movimientos', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Costo Promedio'),
        ),
        migrations.AddField(
            model_name='producto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por'),
        ),
        migrations.AddField(
            model_name='producto',
            name='ean_upc',
            field=models.CharField(blank=True, help_text='Código de barras internacional', max_length=13, null=True, verbose_name='EAN/UPC'),
        ),
        migrations.AddField(
            model_name='producto',
            name='factor_conversion',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='Unidades de venta por unidad de compra', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Factor de Conversión'),
        ),
        migrations.AddField(
            model_name='producto',
            name='ficha_tecnica_url',
            field=models.URLField(blank=True, help_text='URL de la ficha técnica', max_length=500, null=True, verbose_name='URL Ficha Técnica'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='URL de la imagen del producto', max_length=500, null=True, verbose_name='URL Imagen'),
        ),
        migrations.AddField(
            model_name='producto',
            name='impuesto_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('19.00'), help_text='Porcentaje de IVA aplicable', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='IVA (%)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='producto',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AddField(
            model_name='unidadmedida',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True, help_text='Producto activo en el sistema', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='alerta_bajo_stock',
            field=models.BooleanField(default=False, help_text='Indica si el stock está por debajo del mínimo', verbose_name='Alerta Bajo Stock'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción detallada del producto', null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='es_perecedero',
            field=models.BooleanField(default=False, help_text='Producto con fecha de vencimiento', verbose_name='¿Es Perecedero?'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(help_text='Nombre del producto', max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio de venta al público', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Precio de Venta'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='punto_reorden',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Punto para reabastecimiento', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Punto de Reorden'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='requiere_lote',
            field=models.BooleanField(default=False, help_text='Control por número de lote', verbose_name='¿Requiere Lote?'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='requiere_serie',
            field=models.BooleanField(default=False, help_text='Control por número de serie', verbose_name='¿Requiere Serie?'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(help_text='Código único del producto', max_length=50, unique=True, verbose_name='SKU/Código'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_actual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cantidad actual en inventario', max_digits=12, verbose_name='Stock Actual'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_maximo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cantidad máxima permitida', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Stock Máximo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cantidad mínima requerida', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Stock Mínimo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='uom_compra',
            field=models.ForeignKey(help_text='Unidad en la que se compra el producto', on_delete=django.db.models.deletion.PROTECT, related_name='productos_compra', to='core.unidadmedida', verbose_name='Unidad de Compra'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='uom_venta',
            field=models.ForeignKey(help_text='Unidad en la que se vende el producto', on_delete=django.db.models.deletion.PROTECT, related_name='productos_venta', to='core.unidadmedida', verbose_name='Unidad de Venta'),
        ),
        migrations.AlterField(
            model_name='unidadmedida',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='unidadmedida',
            name='codigo',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='unidadmedida',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo'], name='core_produc_activo_a26f35_idx'),
        ),
    ]
