# Generated by Django 4.2.7 on 2025-11-08 03:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProveedorProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lead_time', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proveedor')),
            ],
            options={
                'unique_together': {('proveedor', 'producto')},
            },
        ),
        migrations.AddField(
            model_name='proveedor',
            name='productos',
            field=models.ManyToManyField(blank=True, related_name='proveedores', through='core.ProveedorProducto', to='core.producto'),
        ),
    ]
