# Generated by Django 4.2.7 on 2025-11-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_proveedorproducto_proveedor_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedorproducto',
            name='activo',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='es_proveedor_preferente',
            field=models.BooleanField(default=False, verbose_name='Proveedor preferente'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='lead_time',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Lead time (días)'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='pedido_minimo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Pedido mínimo'),
        ),
        migrations.AddField(
            model_name='proveedorproducto',
            name='es_proveedor_preferente',
            field=models.BooleanField(default=False, verbose_name='Proveedor preferente'),
        ),
        migrations.AddField(
            model_name='proveedorproducto',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proveedorproducto',
            name='pedido_minimo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Pedido mínimo'),
        ),
        migrations.AlterField(
            model_name='proveedorproducto',
            name='lead_time',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Lead time (días)'),
        ),
    ]
