# Generated by Django 4.2.7 on 2025-11-08 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_proveedorproducto_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedorproducto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
