# Generated by Django 4.2.7 on 2025-11-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_proveedorproducto_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock_actual',
            field=models.IntegerField(default=0, help_text='Cantidad actual en inventario', verbose_name='Stock Actual'),
        ),
    ]
