# Generated by Django 4.2.7 on 2025-11-09 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_producto_stock_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.proveedor', verbose_name='Proveedor'),
        ),
    ]
