# Generated by Django 4.2.7 on 2025-11-09 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_movimientoinventario_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='cantidad',
            field=models.IntegerField(verbose_name='Cantidad'),
        ),
    ]
