# Generated by Django 5.2.8 on 2025-11-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_movimientoinventario_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('EDITOR', 'Editor'), ('LECTOR', 'Lector'), ('VENDEDOR', 'Vendedor'), ('BODEGA', 'Bodeguero'), ('SUPERVISOR', 'Supervisor')], default='LECTOR', max_length=20, verbose_name='Rol'),
        ),
    ]
