# Generated by Django 5.2.8 on 2025-11-19 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='bloqueado',
            field=models.BooleanField(default=False, verbose_name='Bloqueado por intentos'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='intentos_fallidos',
            field=models.PositiveIntegerField(default=0, verbose_name='Intentos fallidos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('BODEGA', 'Bodeguero'), ('CONSULTA', 'Consulta')], default='LECTOR', max_length=20, verbose_name='Rol'),
        ),
    ]
