# Generated by Django 5.2.8 on 2025-11-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_eventoauditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ultima_modificacion_password',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última modificación de contraseña'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ean_upc',
            field=models.CharField(blank=True, db_index=True, help_text='Código de barras internacional', max_length=13, null=True, verbose_name='EAN/UPC'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, db_index=True, help_text='Marca del producto', max_length=100, null=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(db_index=True, help_text='Nombre del producto', max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(db_index=True, help_text='Código único del producto', max_length=50, unique=True, verbose_name='SKU/Código'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='ciudad',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='razon_social',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='region',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Región'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='rut',
            field=models.CharField(db_index=True, help_text='Formato: 12345678-9', max_length=12, unique=True, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='bloqueado',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Bloqueado por intentos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido')], db_index=True, default='ACTIVO', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('BODEGA', 'Bodeguero'), ('CONSULTA', 'Consulta')], db_index=True, default='LECTOR', max_length=20, verbose_name='Rol'),
        ),
    ]
